[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "asminpoudel35-debug", email = "asminpoudel35@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.20.0",
    "argon2-cffi>=25.1.0",
    "fastapi>=0.141.1",
    "passlib[bcrypt]>=1.7.4",
    "psycopg[binary]>=3.3.6",
    "pydantic[email]>=2.13.5",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
