"""add

Revision ID: 042f3a8e909f
Revises: 8ddae40f2207
Create Date: 2026-09-27 21:25:37.108436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042f3a8e909f'
down_revision: Union[str, Sequence[str], None] = '8ddae40f2207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Addtocart',
    sa.Column('cartid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['Products.pid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cartid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Addtocart')
    # ### end Alembic commands ###
