"""add

Revision ID: af089e0c7ee1
Revises: 042f3a8e909f
Create Date: 2026-09-27 21:52:50.921106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af089e0c7ee1'
down_revision: Union[str, Sequence[str], None] = '042f3a8e909f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('wishlistid', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Products.pid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wishlistid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist')
    # ### end Alembic commands ###
